apiVersion: 1

datasources:
  - name: Postgres
    type: postgres
    access: proxy
    url: postgres:5432
    database: lvlup
    user: lvlup
    secureJsonData:
      password: lvlup
    jsonData:
      sslmode: disable
      postgresVersion: 1600
      maxOpenConns: 5
    isDefault: true
